version: '3.1'

networks:
  network:
    driver: bridge

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0"
    networks:
      - network
  
  postgresql:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_13:/var/lib/postgresql_13/data
    networks:
      - network

  postgres-test:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
    networks:
      - network
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql
    networks:
      - network
